backend/001-auth-system.sql
backend/008-pantry.sql
backend/009-authorize-meal-designer.sql
backend/010-shopping-list.sql
backend/db-reset.sh
backend/seed.sql

created shopping list, authorize meal designer function, seed data for meal plan entry, meal plan

created shopping list

---

README.md
backend/db-reset.sh

Now you can have your postgraphile server running and just run `./db-reset.sh` and postgraphile will pick up the changes dynamically. 💥

reset database without having to restart postgraphile

---

admin-interface/.gitignore
admin-interface/package-lock.json
admin-interface/package.json
admin-interface/src/html/index.html
admin-interface/src/js/apollo.js
admin-interface/src/js/app.jsx
admin-interface/src/js/index.js
backend/.dockerignore
backend/Dockerfile
backend/db-reset.sh
backend/ops/.gitignore
backend/ops/README.md
backend/ops/main.tf
backend/package-lock.json
backend/package.json
backend/server.js
backend/setup-user.sql
docker-compose.yml

This address #105 . I've tested this and the app is currently available on http://fast-everglades-80450.herokuapp.com/graphiql
This also setups up the plumbing for the admin interface using react-admin and the postgraphile plugin that I discovered.

Setup admin interface

---

backend/004-meal.sql
backend/migrations/000-25_add_meal.sql
meal-planner-fredericton-ui/src/catalog/DisplayMeal.jsx
meal-planner-fredericton-ui/src/components/starRating/StarRating.jsx

Created a React component for 5-star ratings

Added Nutritional Rating

---

admin-interface/Dockerfile
admin-interface/package-lock.json
admin-interface/package.json

admin interface restored

---

backend/seed.sql

No major change, just added more meal data to seed.sql

Added another meal to the test data

---

README.md

Added Windows version of the database seediing.

Added some instructions for completely wiping the docker environment.

---

meal-planner-fredericton-ui/public/translations/en/common.json
meal-planner-fredericton-ui/src/dashboard/Dashboard.jsx

Added an 'All' option to the dropdown.

Fixed #205 Relabeled to 'Assignee' and add and 'All' option

---

meal-planner-fredericton-ui/src/displayMeal/DisplayMeal.jsx

Hacked in a fix for the ingredient display because it was bugging me

Fixed the display of the ingredient list because it was bugging me

---

meal-planner-fredericton-ui/src/core/header/Header.jsx
meal-planner-fredericton-ui/src/dashboard/Dashboard.jsx

Fix #200
Added 'Uassigned' to the filter logic
Removed silly circles from Dashboard, move Meals to the Header

Fix #205 Added 'Uassigned' to the filter logic

---

meal-planner-fredericton-ui/src/core/header/Header.jsx
meal-planner-fredericton-ui/src/planpage/MealPlansToolbar.jsx

It's hidden for now, until there's a shopping list page

Removed shopping list for #200 and updated the drop-down on Save for #206

---

backend/007-meal-plan-entry.sql
meal-planner-fredericton-ui/src/dashboard/Dashboard.jsx
meal-planner-fredericton-ui/src/index.jsx

Delete Dialog React component added in dashboard. Changed the sql for mealplan entry to cascade on delete of mealplan. This is for Mark Smith. @Ciseal

Delete Dialog React component added in dashboard, delete on cascade for mealplan entry

---

meal-planner-fredericton-ui/src/ShoppingList/ShoppingList.jsx

Added a print button. When printing the header, footer and the print icon is hidden.

#30 Print Shopping List

---

backend/007-meal-plan-entry.sql
backend/012-duplicate-meal-plan.sql
backend/Dockerfile
backend/migrations/003-236-duplicate-meal-plan.sql
meal-planner-fredericton-ui/public/translations/en/meal.json
meal-planner-fredericton-ui/src/planpage/DuplicateMealPlan.jsx
meal-planner-fredericton-ui/src/planpage/MealPlanAssignment.jsx
meal-planner-fredericton-ui/src/planpage/MealPlansToolbar.jsx

Implemented a function for duplicating meal plan by meal designer and admin in the backend

Duplicate meal plan function

---

meal-planner-fredericton-ui/src/core/header/Header.jsx

Query with GraphQL and display the current user in Header

Get and display username in Header making a graphQL query

---

.gitignore
docker-compose.yml
hooks/pre-commit.sh
meal-planner-fredericton-ui/src/planpage/DuplicateMealPlan.jsx
meal-planner-fredericton-ui/src/planpage/MealPlanAssignment.jsx
meal-planner-fredericton-ui/src/planpage/MealPlansToolbar.jsx
meal-planner-fredericton-ui/src/planpage/PlanPage.jsx

Aligned the buttons and reduced the space so that the calendar is viewable without scrolling.

265 toolbar layout

---

docker-compose.yml

Fixes #273 Removed the volume mount for package-lock.json

---

admin-interface/.env
admin-interface/src/js/app.jsx
meal-planner-fredericton-ui/.env

Updates to match schema changes from clients -> people

Fixes #275 Updated path and node names from clients to people

---

backend/Dockerfile
backend/hooks/auth_hook.js
backend/package-lock.json
backend/package.json
backend/server.js
backend/start_postgraphile.sh

address #290
part of epic #250

[#290] - move backend auth to sessions

---

mealplanner-ui/src/pages/MealPlans/CreateMealPlan.tsx

Fixed the bug in 'Create' button in Create Meal Plan form. Please review it and let me know what you think!

349 fix create button

---

backend/meal_seed.sql
mealplanner-ui/src/layouts/Footer.tsx
mealplanner-ui/src/pages/MealPlans/MealPlanHeader.tsx
mealplanner-ui/src/pages/MealPlans/MealPlans.tsx

[#384] - Update the http links to https for photo urls of recipes. They don't appear in production.
@shanthisa
[#385] - Add Footer - feedback link and text
[#386] - When a meal is added to the meal calendar and back button is…

V2 - Fixed two bugs related to images not appearing properly in meal plan and added the footer feedback link

---

.github/ISSUE_TEMPLATE/config.yml

Creating Issue and pull request templates in prep for the next backlog grooming

Disabling blank templates

---

.github/ISSUE_TEMPLATE/config.yml

More prep work for upcoming meeting

Adding contact link for other issues

---

.github/ISSUE_TEMPLATE/epic.md

**Describe the technical changes contained in this PR**
Be clear about purpose and scope of the change
**Previous behaviour**
Describe the product behaviour before this change, if relevant
**New behaviour**
Describe how product behaviour is altered by this change
**Related issues addressed by this PR**
List issue numbers using the "Fixes #xxx" syntax
**Have the following been addressed?**

Adding an epic template

---

.github/ISSUE_TEMPLATE/epic.md

**Describe the technical changes contained in this PR**
Be clear about purpose and scope of the change
**Previous behaviour**
Describe the product behaviour before this change, if relevant
**New behaviour**
Describe how product behaviour is altered by this change
**Related issues addressed by this PR**
List issue numbers using the "Fixes #xxx" syntax
**Have the following been addressed?**

Forgot the template header

---

.github/ISSUE_TEMPLATE/custom_form.yml

**Describe the technical changes contained in this PR**
Be clear about purpose and scope of the change
**Previous behaviour**
Describe the product behaviour before this change, if relevant
**New behaviour**
Describe how product behaviour is altered by this change
**Related issues addressed by this PR**
List issue numbers using the "Fixes #xxx" syntax
**Have the following been addressed?**

Testing out github forms
